### ISSUE TITLE
Bug - Odd error screen appears when multiple browser windows are open and accessing the survey123 website

### ISSUE THREAD

**Issue by bethanyw** [tedrick/Survey123-Testing#62] opened 2017-10-10 18:11 UTC
**Application:** Website

**Device:** Windows

**Operating System:** Windows 7 Enterprise

**Browser:** Chrome

**Error Description:** 

"surveyResultViewer.surveyErrMsg

///////////// TODO: need i18n here ////////////
go back to My Surveys page"

Image attached

![2017-10-10_14-02-05](https://user-images.githubusercontent.com/24254787/31402663-acb2a87e-adc4-11e7-9ed5-ee26a4ab2a22.jpg)

**How to reproduce:**

1) Use one Chrome browser window to access survey123dev.arcgis.com and log into AGOL
2) Click on a specific survey and go to the data tab
3) In another window, connect survey123dev.arcgis.com to an Enterprise environment
4) Go back to the window where survey123 is connected to AGOL and refresh the page
5) Error page from screenshot appears

**Have you tested with another survey?**

**Comment by zhif7782** [comment] 2017-10-11 10:27
Hi @bethanyw , seems you are hitting the unfinished string :) 

Logically, this is expected. Since after a second login in the same browser, the user identity will become the second user, where the second user just cannot access the survey belongs to the first user.

**Comment by JohnHasthorpe** [comment] 2017-10-12 06:41
Expected behaviour - closing issue in preparation for next round of holistic testing.

**Closed by JohnHasthorpe** 2017-10-12 06:41 UTC
