### ISSUE TITLE
BUG : Compromised formatting of screenshots when viewing content in 'Discussions' tab within the side panel of Survey123 Connect 

### ISSUE THREAD

**Issue by BKArmstrong** [tedrick/Survey123-Testing#52] opened 2017-10-10 16:55 UTC
**Application:**
![survey123connect_sidepanel_discussions](https://user-images.githubusercontent.com/6314443/31399596-b524d25c-ada1-11e7-9d8f-91c682c81d42.PNG)
 Survey123 Connect

**Device:** Desktop

**Operating System:** Windows 7 64bit

**Browser:** _For the website_

**Error Description:** 

**How to reproduce:**

**Have you tested with another survey?**

**Comment by tedrick** [comment] 2017-10-11 21:05
Dupe of #55

**Closed by tedrick** 2017-10-11 21:05 UTC
