### ISSUE TITLE
Multiline images and feature reports

### ISSUE THREAD

**Issue by sarahallerton** [tedrick/Survey123-Testing#394] opened 2020-09-17 06:04 UTC
If you download the sample template, you can generate a feature report but if you try to add in a field that is an image multiline field to an existing template, it fails and says it’s not recognised. The survey has been published but the field doesn't seem to be visible in the database. I have noticed that the field is not visible in the database for all multiline image pictures.
![image](https://user-images.githubusercontent.com/48110084/93425536-4fafc880-f90e-11ea-948a-a83585a7ff3e.png)

There is a image field missing where the yellow line is:
![image](https://user-images.githubusercontent.com/48110084/93425669-91407380-f90e-11ea-9a79-d9161a27f010.png)

I have tried the syntax:
${#mphoto}
${$file | size:460:0}
${/}

as well as the original ${mphoto} and they are both erroring when trying to upload the feature report template. 
I have also tried copying and pasting the formatting for the template into a new word document and it still errors when uploading to Survey123 website.

I tried updating the template in ArcGIS Online and it errored when trying to generate a sample report.

**Comment by jim-moore** [comment] 2020-09-18 06:25
I'm unable to reproduce this issue; adding the syntax as above for a multiline image question displays the images as expected. Individual record sample template also works without issue. From the error message, it looks like there's a `${mphoto}` placeholder in the template, which could be the issue as it's expecting ${#mphoto}`? Or perhaps this syntax has been used inside a repeat?

@sarahallerton would it be possible to share your DOCX templates (both the sample that works and the edited version that doesn't) so we can troubleshoot? Many thanks.

@zhif7782 @marikavertzonis

**Comment by sarahallerton** [comment] 2020-09-21 04:34
Hi Jim,

The syntax is from within a repeat yes! Do you reckon that is what is causing the issue?

I have done a bit of googling and for the vphoto field (row 149) I believe that the syntax is: ${#vehicles}${vphoto}${/vehicles}
Is this correct?

Cheers,
Sarah


Sarah Allerton
GIS Technical Advisor | Professional Services
Eagle Technology Group Ltd
Wellington
E: Sarah_Allerton@eagle.co.nz<mailto:Sarah_Allerton@eagle.co.nz>
T: (04) 802 1038  M: (+64) 27 259 7401
W: www.eagle.co.nz<http://www.eagle.co.nz/>
[Eagle_Tech]

**Comment by jim-moore** [comment] 2020-10-20 02:38
> From: Jim Moore 
> Sent: Monday, 28 September 2020 8:20 PM
> To: 'Sarah Allerton' <Sarah_Allerton@eagle.co.nz>
> Subject: RE: [tedrick/Survey123-Testing] Multiline images and feature reports (#394)
> 
> Hi Sarah
> 
> Thanks for sending through the XLSForm and apologies for not getting back to you sooner.
> 
> From the XLSForm, it looks like the vphoto question is a single image question (does not have multiline appearance) and is also inside the vehicles repeat.
> 
> As you mentioned in your earlier email, for this to work in a report template the question would have to be inside repeat tags (the repeat open/close tags tell the feature report engine which layer to look at – in this case the vphoto question needs to be retrieved from the vehicles layer). For example:
> 
> ${#vehicles}
> ${vphoto | size:300:0}
> ${/}
> 
> The syntax for multiline image questions is similar to that for repeats (with open/close tags); but note that a multiline image question inside a repeat would still need to be placed inside its repeat tags in the template. For example:
> 
> ${#vehicles}
> ${#vphoto}
> ${$file | size:300:0}
> ${/}
> ${/}

**Comment by jim-moore** [comment] 2020-10-20 02:41
Followed up with Sarah today (Oct 20) and my reply [above](https://github.com/tedrick/Survey123-Testing/issues/394#issuecomment-712550965) was sufficient. Not a bug -closing this issue.

**Closed by jim-moore** 2020-10-20 02:41 UTC
Labels: A - Website, bug
