### ISSUE TITLE
Creating a new survey via Web Designer - Survey123 Enterprise

### ISSUE THREAD

**Issue by DerekLaw** [tedrick/Survey123-Testing#272] opened 2019-10-17 18:19 UTC
Web Designer - Survey123 Enterprise
Windows Server 2019 Standard
Browser: FireFox

I attempted to create a new survey several times in Web Designer - Survey123 Enterprise. I was able to submit the initial name, tags, summary etc and hit create. After several mins I get this message:

![ErrorMsg1](https://user-images.githubusercontent.com/1037228/67035969-90380e00-f0cf-11e9-8eeb-463c669e8192.png)

Error message is not really helpful. When I dismiss the error message and refresh the survey123 gallery page, I see the survey item:

![ErrorMsg2](https://user-images.githubusercontent.com/1037228/67036074-cb3a4180-f0cf-11e9-87d3-046357dedcb0.png)

but when I attempt to open it and access design mode, I get this message:

![ErrorMsg3](https://user-images.githubusercontent.com/1037228/67036180-fcb30d00-f0cf-11e9-97f8-2ad90c4cc9d0.png)

This happened several times.

I had to manually delete the surveys from the survey gallery page - as something was partially created. Side note: I checked the Portal contents and no survey folders were created.

**Comment by DerekLaw** [comment] 2019-10-17 21:10
**UPDATE:** After the certificate update, I am now able to publish a survey from web Designer to Enterprise. Works as expected. 

However, when opened the survey as a web form to try and submit a survey, I noticed the following:

1. The basemaps do not load for the geopoint question

![missingBasemap](https://user-images.githubusercontent.com/1037228/67047607-7f939200-f0e7-11e9-8e54-6dacdb45cf1d.png)

2. For the image question, when I try to take a photo, the web form does not seem to work with the camera on my computer; question

![camera1](https://user-images.githubusercontent.com/1037228/67047758-cc776880-f0e7-11e9-82c3-b0030775e449.png)

click the camera and see this,

![camera2](https://user-images.githubusercontent.com/1037228/67047767-d0a38600-f0e7-11e9-891a-b40ae382ed76.png)

**Comment by zhif7782** [comment] 2019-10-18 12:52
@oopsliu , besides the creation issue probably is caused by the behind portal/server (we tested this env. yesterday), could you have a try on the geopiont question issue and the image webcam issue?
* geopoint: may be caused by cannot access the underlying web map in the portal for some reason. If this is the case, similar to https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/3434. 
* webcam: not sure if it's due to the SSL certificate is not trusted...

**Comment by oopsliu** [comment] 2019-10-22 09:37
I'm able to reproduce the geopoint question issue with holistic Portals, but unable to reproduce it with AGOL, internal issue: https://devtopia.esri.com/Melbourne/Survey123-OnPremises/issues/22

**Comment by BrandonArmstrong** [comment] 2019-10-31 18:46
@DerekLaw Thanks for testing and comments
@oopsliu Closing this issue and can continue testing in internal issue

**Closed by BrandonArmstrong** 2019-10-31 18:46 UTC
