### ISSUE TITLE
FEEDBACK: GNSS (2)- your form, our feature service, our webhook

### ISSUE THREAD

**Issue by marikavertzonis** [tedrick/Survey123-Testing#139] opened 2018-08-29 01:34 UTC
This scenario allows you to create a survey in your org that points to our exisitng feature service. It will also allow you to explore the concept of webhooks even if you dont have access to your own webhook service.

1) take this survey and publish it in your own org.
    - drag and drop the spreadsheet  [Street Lights.xlsx](https://github.com/tedrick/Survey123-Testing/files/2330382/Street.Lights.xlsx) on the new survey tile of Connect
    - copy this image to the media folder
![streetlights](https://user-images.githubusercontent.com/5713624/44759954-01d99380-ab80-11e8-99a4-fe13580cd9f5.png)
    - publish your survey

2) Browse to this new survey on survey123.arcgis.com and go to the settings page
    - create a new webhook
    - name it and add this payload url
https://prod-18.westus.logic.azure.com/workflows/76327681e9634860badf97f341c5a2e8/triggers/When_a_survey_response_is_submitted/versions/08586661024357910366/run?api-version=2016-06-01&sp=%2Ftriggers%2FWhen_a_survey_response_is_submitted%2Fversions%2F08586661024357910366%2Frun%2C%2Ftriggers%2FWhen_a_survey_response_is_submitted%2Fversions%2F08586661024357910366%2Fread&sv=1.0&sig=grIdYwkKdBC8tWOD8IB_7XX8IK3WgdRGBXUnYE6yg8Q

the page should looks something like this

![streetlightwebhook](https://user-images.githubusercontent.com/5713624/44760014-436a3e80-ab80-11e8-9684-8471a51e59f4.PNG)

    - click save

3) Sign in to Survey123 on your device and download this new survey that you published

4) connect a GNSS receiver to your device. Follow steps on EAC https://earlyadopter.esri.com/project/article/item.html?cap=e69ef91f45744b98882c651f7b518eb7&arttypeid={5a8e51ed-4a87-43fe-a67d-2b7829af130f}&artid={9AEF4173-09CC-4134-9811-0AA2B3B405DD}

5) go outside and collect the 3 points described in the survey

6) send the records from the field (if you have data connection) or send upon return to the office
    - see the notification emails in the meeting room
    - take a look at the points collected in the feature service here http://www.arcgis.com/home/item.html?id=0921493eec9844b4affcf02f1e9c2200

**Comment by JohnHasthorpe** [comment] 2018-08-30 00:45
- Britany
- Chris
- Gareth
- Paul
- Ryan

**Comment by BrittanyDahl** [comment] 2018-08-30 03:33
Thanks for running our group through this @marikavertzonis !

My feedback from this session is as follows:

-Issue identified in the field: Trouble Signing in 
Method: Opened the Survey123 3.2.46 Alpha Field app, and signed in. Went outside to collect data, and found that I was signed out of my organisation. It would not let me sign back in (left with loading circle) until I closed the app, and then re-opened it. This was after I had connected my GNSS Device and then downloaded the survey. 

-Adding Survey123 Microsoft Flow templates would be very useful

-In Microsoft Flow, when using "Send email" and typing in the body, - it would be great if the dynamic content was listed with reference to the question in Survey123 the field comes from

- Flow dynamic content "feature position" not filling in information after sending an email.

- Web hooks could be named better  in the Survey123 Web App  

- As was discussed, we would recommend having really detailed instructions. Especially highlight the importance in re-downloading/re-freshing a survey once ANY changes are made (eg. web hooks!)

- When creating a survey from a feature service (from a .xlsx with the submission_url listed) make sure to make the name of the survey (when creating a new survey from a file), to be the same name as the feature service. Otherwise the error is "table not found".

**Comment by paul-gpsit** [comment] 2018-08-30 04:11
Followed the steps and got it working. When we downloaded the spreadsheet, it was called "Street.Lights.xlsx" (note the period between Street and Lights) and the survey wouldn't publish. The fix seemed to be to rename the file to "Street Lights.xlsx" (note the space) to match the content within the spreadsheet.
(Fix as figured out by Brittany)

**Comment by JohnHasthorpe** [comment] 2018-09-03 06:10
@BrittanyDahl Please can you expand:

> -Adding Survey123 Microsoft Flow templates would be very useful
What would these templates include?


-In Microsoft Flow, when using "Send email" and typing in the body, - it would be great if the dynamic content was listed with reference to the question in Survey123 the field comes from



Flow dynamic content "feature position" not filling in information after sending an email.

Web hooks could be named better in the Survey123 Web App

As was discussed, we would recommend having really detailed instructions. Especially highlight the importance in re-downloading/re-freshing a survey once ANY changes are made (eg. web hooks!)

When creating a survey from a feature service (from a .xlsx with the submission_url listed) make sure to make the name of the survey (when creating a new survey from a file), to be the same name as the feature service. Otherwise the error is "table not found".

**Comment by JohnHasthorpe** [comment] 2018-09-03 06:15
Created documentation enhancement issue (arcgis-survey123/issues/962)  to address:

> As was discussed, we would recommend having really detailed instructions. Especially highlight the importance in re-downloading/refreshing a survey once ANY changes are made (eg. web hooks!)

**Comment by BrittanyDahl** [comment] 2018-09-03 07:08
Hi John, Please see below for further information:

Issue 1. Upon entering the Microsoft Flow page - you have the ability to search for templates. 
https://australia.flow.microsoft.com/en-us/ Yet, there isn't any Survey123 Templates available yet, and you have to create your own. Any chance a template will be created in the future?
![image](https://user-images.githubusercontent.com/20454586/44972219-fe347b00-af8a-11e8-82f2-0ca6d3b1e5b2.png)

Issue 2. I think you can close this issue. 
In the tutorial steps we followed above, the name of the Web hooks could have been a little more descriptive in the Survey123 Web App. If you see my screenshot below - I have no idea which flow relates to which process I set up. However, I am assuming I could have put in my own name in the "name" box, and, as you can edit and change the name, I think the issue is with the steps listed above and not the web app itself. However, I absolutely required the steps above to get my head around web hooks, so I highly recommend having these sort of tutorial steps available somewhere!). 
![image](https://user-images.githubusercontent.com/20454586/44970512-a266f380-af84-11e8-89c6-aa6ed3c0bd72.png)

**Closed** 2019-01-14 18:17 UTC
