### ISSUE TITLE
CHALLENGE: Verifications on ArcGIS Enterprise

### ISSUE THREAD

**Issue by IsmaelInRedlands** [tedrick/Survey123-Testing#10] opened 2017-08-25 22:38 UTC
**Context:** In this challenge we  provide you with a set of simple scenarios  to test Survey123 against ArcGIS Enterprise. Testing this suite of exercises and documenting your findings will take you about 60 minutes.

```
https://pm.demo.geocloud.com/arcgis
Username: enterprisepub
Password: Password123!
```

**Challenge:** For each of the tests outlined in this issue, please add comments indicating if the test passed or failed for you.

1) Configure the Survey123 website at https://survey123.arcgis.com against the ArcGIS Enterprise instance  above.  This test  passes if you are able to publish a simple  survey using Web Designer against ArcGIS Enterprise using https://survey123.arcgis.com 

2) Configure a survey using photos and test it. This test  passes if you are able to submit 5 records into ArcGIS Enteprise containing each at least one photo attachment. Add at least a geopoint, text, date, integer and image question into your survey.

3) Configure the survey in test 2 with the Inbox  capability enabled. This test passes if you are  able to edit  existing features from ArcGIS Enterprise using the  Inbox.

4) Test Copy and Edit  functionality. This test  passes if you are able to copy a survey from the Sent folder in your mobile app, copy it, edit  some attributes  and successfully post this new feature into ArcGIS Enterprise.

5) Data export: This test passes if you are able to export the data submitted  into ArcGIS Enterprise to filegeodatabaase format using the Export function in the https://survey123.arcgis.com website.

6) Analyze page: This test passes if you are able to successfully look at your data using the Analyze tab of the Survey123 website.

**Comment by tedrick** [comment] 2017-08-29 17:24
Christian, Bethany

**Comment by bethanyw** [comment] 2017-08-29 18:44
Challenge 1 results: Failed.

My workflow:
1) I accessed my own 10.5.1 portal to do this via the following URL:
https://survey123.arcgis.com?portalUrl=https://supt0000288.esri.com/portal
2) I signed in, and clicked "Create a New Survey"
3) I added one singleline text field > Publish > Failed
4) Error: "Unable to publish the survey. {"code":-1,"message":"","success":false}
5) When I go into my content in portal, I see the feature class and the feature service were created
6) However, the survey then does not show up in the Survey123 Field app

Fiddler capture: 
[Challenge1.zip](https://github.com/tedrick/Survey123-Testing/files/1261362/Challenge1.zip)

**Comment by zhif7782** [comment] 2017-08-31 07:06
Hi @bethanyw , seems the portal `https://supt0000288.esri.com/portal` is deployed in our internal network and cannot be accessed from the internet. If yes, then publish failed is an expected behavior due to the publish process requires server side operation from the Survey123 website, and the server side is located out of Esri's internal network.

**Comment by bethanyw** [comment] 2017-08-31 12:54
Hi @zhif7782 thanks for reaching out. You are correct, that Portal is internal only. I didn't realize that the Portal needed to be public facing for this to work. Publishing from Survey123 Connect to this Portal works.

**Comment by zhif7782** [comment] 2017-09-01 11:25
@bethanyw thanks for the confirmation. There has a difference between Survey123 website and Survey123 Connect during publishing:
* In Survey123 website, interaction with Portal during publishing is handled by the remote server (in public cloud)
* In Survey123 Connect, interaction with Portal during publishing is handled by Survey123 Connect software it self, not by the remote server, so the Connect can access the Portal since it's running on your computer inside Esri network

So if you connect the hosted website (https://survey123.arcgis.com) with a portal:
* If the portal can be accessed through the internet, the website will be fully functional
* If the portal is in an internal network, except the Design page (actually only the Publish button), other parts of the website will be functional
* If you want the website fully functional against an internal portal, you need our on-premises installation of Survey123 :)

**Comment by bethanyw** [comment] 2017-09-01 12:11
Hi @zhif7782. Ahhh, I understand. Thank you for this clarification-- it's really helpful! Will this be documented-- that a Portal must be public facing for publishing from the website to succeed? I think that will be a point of confusion for customers and support analysts.

Thanks again!

Best,
Bethany

**Comment by zhif7782** [comment] 2017-09-04 12:14
Hi @bethanyw , as far as I know, connecting https://survey123.arcgis.com to a portal by using the `?portalUrl=` URL parameter is an internal approach and has not been documented yet, so there's no document for the above hints.

For on-premises deployment cases where portal instead of ArcGIS Online needs to be connected, we encourage users to use our on-premises installer for Survey123 instead.

**Comment by JohnHasthorpe** [comment] 2017-10-10 05:17
2.4 Completed - Closing

**Closed by JohnHasthorpe** 2017-10-10 05:17 UTC
Labels: Type: Challenge, v-2.4
