### ISSUE TITLE
Geometry seems to be missing from submitted surveys

### ISSUE THREAD

**Issue by DerekLaw** [tedrick/Survey123-Testing#279] opened 2019-10-17 21:28 UTC
Survey123 Enterprise installed on ArcGIS Enterprise 10.7.1
Windows Server 2019

I was able to use Web Designer in Survey123 Enterprise and created a new survey, without a geopoint question. Published and completed 2 new surveys. When I view in the Survey123 Enterprise website, I can see the submitted data, but under the Data tab, I don't see any points on the map. Seems like the geometry info is missing to me,

![missinggeometry](https://user-images.githubusercontent.com/1037228/67049119-57f1f900-f0ea-11e9-8ce7-8fdcb00724e0.png)

**Comment by DerekLaw** [comment] 2019-10-17 21:48
Test #2 

I created and published a survey with a geotrace question in Survey123 Connect to Portal. The survey created successfully, but when I open to try and submit as a web form, I see this:

![geotrace](https://user-images.githubusercontent.com/1037228/67050332-1dd62680-f0ed-11e9-9177-fb019e54bd51.png)

It looks like the geotrace question is not loading properly.

**Comment by zhif7782** [comment] 2019-10-18 12:15
Hi @DerekLaw , the first issue is a bug in the web app https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/3811#issuecomment-1865357 and we just fixed this in today's 3.6 hotfix. The fix is available on https://survey123.arcgis.com now and will be available in the next build on-premises installation.

For the second issue, I think it may relate to the combination of the on-premises code+testing portal since the geotrace question from Connect works as expected on the online web app. @BrandonArmstrong can you please help on this or share the info of the testing env.?

**Comment by BrandonArmstrong** [comment] 2019-10-21 16:29
@zhif7782 this is the same behavior highlighted in https://devtopia.esri.com/Melbourne/Survey123-OnPremises/issues/22.  All VM's shared should be capable of reproducing the error

**Comment by brettstokes** [comment] 2019-11-01 01:12
closing as internal has been logged

**Closed by brettstokes** 2019-11-01 01:12 UTC
