### ISSUE TITLE
CHALLENGE: Recording audio

### ISSUE THREAD

**Issue by IsmaelInRedlands** [tedrick/Survey123-Testing#2] opened 2017-08-24 21:54 UTC
**Requirements:** Survey123 Field App and Connect from Early Adopter community: https://earlyadopter.esri.com/project/home.html?cap=%7bE69EF91F-4574-4B98-882C-651F7B518EB7%7d or from test-flight for IOS (you will need to download the test flight app from the store and receive an invite from Esri).

-----------------------------------------------

**Context:** With version 2.4 of Survey123 for ArcGIS, you can record audio from your smart forms. This is, of course, as long as your device has a microphone...  

> Just for fun...you can try [this survey](https://survey123.arcgis.com/share/ff11ba9662984d6e9bc69196ecda06a8?open=native) to have a feel of audio recording in Survey123

![download](https://user-images.githubusercontent.com/5918689/29740080-4a6a0db8-8a03-11e7-868d-7c246aa39d54.png)

> If you like to listen to recordings use this [Web AppBuilder web app](http://survey123.maps.arcgis.com/apps/webappviewer/index.html?id=7a63300cc85041389a9fdb138035ba68)

**Challenge:** _Gubernatrix cristata_, or most widely known as Cardenal Amarillo is a rare bird from South America. These birds at  the border of extinction because they are captured as pets. They sing beautifully and people are  willing to pay a lot of money for them...  In this challenge, you will create a survey to help a group of conservationists capture observations of Cardenal Amarillo on the wild. 

1) Author survey including:

> - Date and time of the observation (required and set by default to now)
> - Location (required)
> - Notes  (optional)
> - Audio (required)

We will use the audio question to let field observers record the sing of the Cardenal Amarillo.

2) Once you have authored the survey, we will want you to exercise it in the field. That is, you are going to download the survey into a device with a microphone and then record no less than 5 observations. In each of the observations we will want you to include a recording of no less than 20 seconds each.

`NOTE: Capture all data while not on WIFI. Submit all data while NOT on WIFI.`

3) Finally use the Data tab in the Survey123 website to listen to your audio files. You will not find the audio files in the table view, but if you click on a particular record, you should see the audio link in the Individual Survey Response report. Listen to them to make sure they have been uploaded correctly.

After all the above is achieved, or if at any point  you cannot proceed, please answer the questions below by adding comments to this issue.

'NOTE: If at any point in time during this challenge you get  stuck, please contact Esri staff so we can get you going.

**Questions** 

* Was the documentation good  enough for you to create the survey with the audio question? Describe any issues you may have encountered.

* Were you able to submit all the data correctly? If not, report the error message you got.

* Were you able to listen to your recordings by clicking on the attachment links in your popup web map?

* Was the user experience for capturing audio in the phone/tablet friendly?

* What is the operating system and phone you used for capturing the data?

`NOTE: Copy and answer all questions above into your own comment below.  If you want to add other  type of info into your own comments that is fair too.`

**Comment by tedrick** [comment] 2017-08-29 17:21
Jess, Bethany

**Comment by bethanyw** [comment] 2017-08-29 17:58
Hi @tedrick, I noticed a problem with Survey123 crashing when an audio file is renamed. I tested this with the Windows field app. Do I need to do anything else with that or should I submit a bug on here?

**Comment by odibie** [comment] 2017-08-29 18:06
Hello @bethanyw , please submit as a bug.

**Comment by phil-wilson** [comment] 2017-09-27 05:50
@bethanyw Note issue with renaming audio files on Windows has been addressed and will be resolved in the 2.5 release. Thanks for the bug tip.

**Comment by phil-wilson** [comment] 2017-10-11 04:54
[Audio Example.xlsx](https://github.com/tedrick/Survey123-Testing/files/1374241/Audio.Example.xlsx)

**Comment by JohnHasthorpe** [comment] 2017-10-13 01:09
Deep and Vish

**Comment by swilliamsam** [comment] 2017-10-19 03:33
The playback volume of the recorded audio is very low in the Survey123 iOS app. My device volume is the highest it can go, but the audio i've recorded in the form is barely audible. Im running iOS 11.1 on an iPhone 6s. The audio is full volume on the web app when I view the submission.

**Comment by phil-wilson** [comment] 2017-10-20 00:57
Thanks @swilliamsam. I have done some testing and confirmed the issue is with the playback volume of audio from within Survey123 app.

The volume level of the audio file recorded is normal, if you submit your survey and playback the file in browser (AGOL/Survey123 website), download the file on Windows or to another device and play outside of Survey123 app, the volume level is acceptable.

I have added this as a bug to our development repo.

**Closed** 2018-01-17 19:13 UTC
Labels: Type: Challenge, v-2.4, v-2.5
