### ISSUE TITLE
Feedback: Ranking question

### ISSUE THREAD

**Issue by IsmaelInRedlands** [tedrick/Survey123-Testing#349] opened 2020-05-14 14:31 UTC
The new ranking question in web designer allows respondents to rank a list of items by dragging and dropping each item in order of preference.

![Ranking](https://user-images.githubusercontent.com/5918689/81947200-20cac400-95b5-11ea-8899-be584f5f17f3.gif)

### Feedback
* Does the question work well in online surveys? Test with a small (up to 5) and large list (up to 15).
* Is the user experience for sorting items intuitive?
* Explore the output of this question through the Analyze tab in the Survey123 website. Are the results presented in an intuitive way?
* Test the output of this question in a custom report.

**Comment by tedrick** [comment] 2020-05-14 16:27
Redlands holistic lab session participants (5/14/2020):
Please check your name if you are interested in testing this feature.

- [ ] Adrienne Allegretti
- [ ] Aldous Tsang
- [ ] Bobby Home
- [ ] Brandon Whitney
- [ ] Carlos Maulen
- [ ] Chad Nunemacher
- [x] Charmel Menzel
- [ ] Chris Lesueur
- [ ] Christopher Eby
- [x] Cory Whittaker
- [ ] Dabney Hopkins
- [ ] Jerry Jacobsen
- [ ] Juliano Kersting
- [x] Kevin Deege
- [ ] Kyle Jones
- [ ] Kyle Wikstrom
- [ ] Kylie Donia
- [ ] Leonard Barnhill
- [ ] Melanie Kaminski
- [x] Michael Penokie
- [ ] Mike Cox
- [ ] Nichole Ueberschar
- [ ] Rich Kerr
- [x] Steven Temmermand
- [ ] Theresa Maier
- [x] Zachary Sutherby

**Comment by GI-Maier** [comment] 2020-05-14 17:31
I've created a short list and it worked just fine. 
After creating and publishing the survey with the large ranking list, I wanted to preview the survey in the web designer, but the following error occured: 
{"error":{"code":400,"messageCode":"CONT_00942","message":"Resource already present","details":[]}}

I tried to solve it, by closing the survey and reopening it. I tried to preview now and everything worked just fine.
Therefore, my first testing was successful and I like the feature so far...but I will continue testing more.

**Comment by adgealleg** [comment] 2020-05-14 17:36
- Does the question work well in online surveys? Test with a small (up to 5) and large list (up to 15). **Yes, tested with both and it worked fine**
- Is the user experience for sorting items intuitive? **Yes**
- Does it work in the field app? **Not yet available to test**
- Explore the output of this question through the Analyze tab in the Survey123 website. Are the results presented in an intuitive way? **No results show up under the Analyze tab for the 2 entries I made via the web app**
- Test the output of this question in a custom report. **Wasn't able to Generate the report**

**Comment by menzelc** [comment] 2020-05-14 17:56
Is the user experience for sorting items intuitive? **not exactly.**
Description:
When I'm ranking, I get the red box indicating "Please rank all the choices for this question".  This red box and comment does not go away unless I actually move each choice.  My case I don't need to move each item to get the ranking I want to submit.

My scenario:
5 choices.  I move several rankings.  The 5th item/choice is where I want it to be but the red box remains unless I move every rank.  To me that isn't user friendly.
Test for yourself:
Create a ranking with 5 choices, move the top 4 but not the 5th (bottom choice).

**Comment by kyliedonia** [comment] 2020-05-14 17:57
I'd still like a bit of flexibility with the ranking that I don't seem to have now:

1. Perhaps I want to allow users to not have to rank all of them, and leave a set if "unranked" or "equally last" at the bottom of the list. As the survey creator, right now, I don't know which items are "tied for last" or ignored by the user as the user has to rank them and would probably just randomly set them to be able to submit.
2. Related to my first point, I as the author might care about the users "Top X choices" like a top 3, for example. I'd like to be able to say "the user must at least rank 3 of these" (they could still rank all, and I'd like to know what they did, but I want to require a top 3).
3. If not going to allow an "unranked last bunch" think about having the app number the last set for the user instead of making me click on each one to give it a position. Perhaps this would be different for required and not required questions (not sure - something to think about). 
4. I'd like a way to add items to the bottom of the list. Being able to sort from both ends, especially in a long list, helps me to process items as I read them instead of having to keep ignoring the same one that I know will be my last or one of my last in the ranking.
5. I'd like to be able to clear a position. I clicked one on accident and now there is no way to move it out of my list (either by moving to the bottom or by putting it back to unsorted).

Also, this is not intuitive or ideal to me:
- As the person filling out the survey, if the ranking question isn't required, and I order a few of them, I can't submit until I order all. Perhaps I rank a few, realize that I would have to rank more than I want to, and so I just want to move on. I have to explicitly reset to submit, or I get an error. And maybe that would be enough that I'd quit filling out the survey as it is inconvenient.

**The data tab**
1. A space at the end of a value is included in the data stored (for example, I did ice cream flavors and ended up with a "neapolitan_" option in the data. It would be nice to not have to delete and recreate the option for a typo since its hard to see when authoring).
2. Capital letters aren't honored in the data stored, which can make it harder to give a nice display of these in a dashboard, etc. 

**Analyze tab**
- I see a blank chart with my long list of choices (I didn't look while it was a short list). I have multiple data points, but all the choices show average scores of 0.
- The table is blank -- everything is zeros.

**Comment by GI-Maier** [comment] 2020-05-14 17:59
- Does the question work well in online surveys? Test with a small (up to 5) and large list (up to 15).
 _Yes. Just fine._
- Is the user experience for sorting items intuitive?
_Yes._
- Explore the output of this question through the Analyze tab in the Survey123 website. Are the results presented in an intuitive way?
Same happened to me. No results where shown.
[Holistic Testing - Ranking.pdf](https://github.com/tedrick/Survey123-Testing/files/4630101/Holistic.Testing.-.Ranking.pdf)
_
- Test the output of this question in a custom report.
_Worked just fine._

**Comment by menzelc** [comment] 2020-05-14 18:16
Standard UI question:
Is Reset a typical button found on other apps the provide ranking? 
I ask b/c I see the Reset Button but I also was looking for a "set ranking" button.... but that may be too much.

![image](https://user-images.githubusercontent.com/4838513/81970434-89ce2e00-95ed-11ea-9472-01a7f766256a.png)

**Comment by Temmermand** [comment] 2020-05-14 18:31
When I drag up a choice, it numbers a phantom choice.

Repro steps:
1) Author a survey with 19 random choices for the rank. Set as required. Check box to cache.
![image](https://user-images.githubusercontent.com/38793244/81971382-d574dd80-95d5-11ea-9d44-05f1495c6b1c.png)
2) Select 11 choices
![image](https://user-images.githubusercontent.com/38793244/81971459-f806f680-95d5-11ea-96ee-a7f26f2aa877.png)
3) Try to drag (burger bar) choice 10 up between choice 13 and 19
![image](https://user-images.githubusercontent.com/38793244/81971601-2f75a300-95d6-11ea-8919-8e7d9daa2c98.png)
4) A phantom 12 appears next to choice 6.
![image](https://user-images.githubusercontent.com/38793244/81971651-45836380-95d6-11ea-8c68-ff53d17317a8.png)
5) When you let go of the drag, then the phantom 12 goes away.
![image](https://user-images.githubusercontent.com/38793244/81971734-6946a980-95d6-11ea-911d-e971e49f2f86.png)

**Comment by Temmermand** [comment] 2020-05-14 18:45
I see the same as Adrienne. The results of the rank do not show up in the analyze tab.
![image](https://user-images.githubusercontent.com/38793244/81973004-57fe9c80-95d8-11ea-9a2e-b154f1e375ef.png)

**Comment by marikavertzonis** [comment] 2020-05-15 03:39
- [ ] Ben Van Kesteren

**Comment by someevil** [comment] 2020-05-15 05:45
I think the speed issue I was having back on Jan 31st has been resolved. Also there was no error when publishing this time. All good!

**Comment by fendiaoxiaoshuazi** [comment] 2020-05-19 10:06
Thanks all for the feedback!

Unfortunately, the analysis chart and report for ranking did not work properly at that time. This a bug caused by the submission refactor. The results of the ranking question were supposed to be stored as comma-separated lists instead of space-separated lists. Thank you all for catching the bug!

The support for partial ranking is already under consideration, and I have logged your suggestions in our [internal issue](https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/4192).

The enhancement suggestions on UI/UX  are reasonable, I also have logged them in the [internal issue](https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/4375).

**Comment by fendiaoxiaoshuazi** [comment] 2020-05-19 10:17
@Temmermand Thank you for catching the phantom choice. I have logged an [issue](https://devtopia.esri.com/beijing-r-d-center/survey123-hub/issues/4376) for it.

**Comment by fendiaoxiaoshuazi** [comment] 2020-05-19 10:21
Thank you @GI-Maier, we will pay attention to the "Resource already present" error that you encountered.

**Closed** 2020-06-03 17:38 UTC
Labels: A - Website, Type: Feedback
