### ISSUE TITLE
FEEDBACK: Nested Repeats

### ISSUE THREAD

**Issue by phil-wilson** [tedrick/Survey123-Testing#135] opened 2018-08-28 00:42 UTC
Nested repeats allow you to include repeats within repeats. Up until version 3.0, you could add multiple repeats to a survey, but they could not be nested.  This was somewhat limiting. For example, you could author a survey to capture: 

- A building with multiple households (each household would be a record in the repeat), or
- A household that contains multiple people (each person would be a record in the repeat)
   
But now at 3.0 your survey can contain both: 

- A building with multiple households (each household would be a record in the repeat), and
- A household that contains multiple people (each person would be a record in the repeat)

Technically, there is no limit to the number of repeats that you can nest, however if the number of nested repeats gets too large then things might get a bit busy from a UI perspective.

Documentation can be found here: http://doc.arcgis.com/en/survey123/desktop/create-surveys/xlsformrepeats.htm

Example survey: [Nested Repeats.xlsx](https://github.com/tedrick/Survey123-Testing/files/2326061/Nested.Repeats.xlsx)

**Comment by phil-wilson** [comment] 2018-08-28 01:08
We want your feedback on Nested repeats so as part of this feedback issues, try the following:

- Design and publish a survey from Connect
- Include different question types, calculations, defaults, constraints etc in your survey
- Enable the Inbox to test your survey and nested repeats with editing surveys
- Open your survey in the field app and test collecting new surveys, saving to drafts, outbox, sent folders and then also test editing via the inbox, drafts and sent.
- View your submitted surveys on the Survey123 website and AGO to see how the nested repeat layers and tables are created and how the data is related.

**Comment by JohnHasthorpe** [comment] 2018-08-30 00:40
- Daniel
- Neale
- Chris
- Gee

**Comment by Hutcho3151** [comment] 2018-08-30 01:33
Looks good and great you can repeat geopoints, even if child values of the parent record.
It would be good to label the repeat "+" buttons as it may be confused with others to know which nest you are adding to.

**Comment by Hutcho3151** [comment] 2018-08-30 02:15
Seems like a bug in the number of records showing in the inner nested counter after you create a new outer repeat record. May be limited to the second nested record set and then ok for balance.

**Comment by ccounsell** [comment] 2018-08-30 02:31
@Hutcho3151 I also hit that error re showing number of repeats for a new record.

Tier 1 repeat first instance
Tier 2 add 2 records
Tier 3 add 2 records
Tier 4 add 2 records

Go to make a new repeat at Tier 1, Tier4 defaults to showing '1 of 2' with null values.

Repeating for 3 records in each nested table in first instance of Tier 1, second record at tier one has Tier 4 as showing '1 of 3' with null values.

Recieved error on submitting with null or filled out values 'operation rolled back'

**Comment by danmcilroyGA** [comment] 2018-08-30 04:05
**Built using macOS Connect 3.2.35 (Alpha) and captured using iOS Survey123 3.2.46 (from TestFlight)**

dateTime field with a now() didn't update in the second tier repeat one a new record is added at the top level 
![img_3235](https://user-images.githubusercontent.com/40751679/44824249-e8038380-ac47-11e8-97a4-2f94447d8758.JPG)
when you add a second record to the second tier repeat, the dateTime is updated by now()

I was able to recreate this several times.

Barcode scanning appears to work
Photos (both portrait and landscape) appear to work
Multiline text appears to work

first survey failed to upload
![png image](https://user-images.githubusercontent.com/40751679/44824599-d327ef80-ac49-11e8-93c5-5afa4da5d352.png)

We have been unable to determine what the cause of this failure to upload
XLSForm attached here:
[Nested_Repeat_Testing.xlsx](https://github.com/tedrick/Survey123-Testing/files/2334522/Nested_Repeat_Testing.xlsx)

**Comment by Hutcho3151** [comment] 2018-08-30 05:10
Activated the Inbox and edited a previous point from the Inbox and saved it. The second point was incomplete in the Sent data.

**Comment by BrandonArmstrong** [comment] 2018-08-30 22:53
@ccounsell Was the behavior encountered related to the Campsite Survey (Nested Repeats Sample)? 
 If not, please provide XLSForm which led to null values in repeats.

**Comment by JohnHasthorpe** [comment] 2018-09-03 12:16
Issues created for all raised issues::

- Repeat label issue: /issues/1875
- Printing nested repeat issue:/survey123-hub/issues/2792
- The number of records displayed is wrong:  Survey123/issues/2261
- 2nd Tier calculations not firing: Survey123/issues/2546
- Android camera issue: Survey123/issues/2557

Closing

**Closed** 2018-09-03 12:17 UTC
Labels: A - Connect, A - Field App, Type: Feedback, v-3.0

**Comment by unmas-ss** [comment] 2020-11-07 11:12
Is there any solution for this.


![image](https://user-images.githubusercontent.com/53593946/98439487-34d62500-2103-11eb-8bb1-92a048c50e4d.png)
