### ISSUE TITLE
FEEDBACK: Website Designer

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#120] opened 2018-04-27 15:30 UTC
The website is introducing a new question (Single choice grid) and the ability to use rich text in the thank you screen. Try them out and leave some feedback!

**Comment by RITI8169** [comment] 2018-04-27 17:38
**Additional row is added for a Grid question in the Survey123 Field App**
1. Create a Survey on the website 
2. Add a Single Choice Grid question
3. Publish and open the survey in the field App

There is an additional row of Choices below the question apart from the choices for the rows added. This only shows on the Field App and works fine on the website.

See screenshot below.
![grid1](https://user-images.githubusercontent.com/31448327/39376586-0ff9df04-4a07-11e8-9075-4d074d35c7e7.PNG)

**Comment by RITI8169** [comment] 2018-04-27 17:46
**Incorrect default Submitted Date in the S123 form on the website**

1. Create a survey on the website
2. Add a Date question
3. Select the Default Value as Submitted Date
4. Publish and open the survey on the website as well as the Field App

The default submitted date displayed on the website is incorrect and it displays correctly on the Field App.

See screenshot below: It shows 26th April on the website form and displays correctly as 27th April on the Field App. It also displayed 27th April correctly in the Design mode on the website.

![subdate](https://user-images.githubusercontent.com/31448327/39376940-3e687ec6-4a08-11e8-864c-95c646acb12b.PNG)

![subdate2](https://user-images.githubusercontent.com/31448327/39376951-4c0ea5be-4a08-11e8-88c4-a0acea64e4aa.PNG)

**Comment by Shimoorook** [comment] 2018-04-27 17:47
-When multiple 'Single Choice Grid' questions are added. The 'Delete' button doesn't work and the question does not disappear unless refreshed. And when the survey is refreshed, nothing gets saved. 

-The question number for 'Single Choice Grid' is always '1'. No matter how many you add or where you place it. It's always '1'. 

![screenshot 283](https://user-images.githubusercontent.com/18020137/39376945-6d85da32-4a21-11e8-990a-9bae97489135.png)

**Comment by RITI8169** [comment] 2018-04-27 17:57
**_Enhancement:_**

When inputting a phrase (like a full name separated by space) the input is treated as two different entities. It would be good to have the option to treat the phrase as one input in the survey.

![singkephrase](https://user-images.githubusercontent.com/31448327/39377381-c7e23970-4a09-11e8-84d6-7676062facca.PNG)

**Comment by RITI8169** [comment] 2018-04-27 18:14
**Incorrect location displayed for data submitted through S123 website form**

1. Create a survey
2. Publish and open in the website as well as the Field App
3. Submit data using both the website and the App
4. Open the Survey Data tab on the website
5. Select one of the Field App submitted data entry 
    The data is displayed in the correct location (Redlands)
6. Select one of the data submitted from the website
_The selected data is displayed in an incorrect location on the Map._

See screenshots.

**Data submitted through Field App**

![location2](https://user-images.githubusercontent.com/31448327/39378053-15539ae4-4a0c-11e8-80ee-42612bf30c9d.PNG)

**Data submitted through website**

![location1](https://user-images.githubusercontent.com/31448327/39378061-1c7bc54e-4a0c-11e8-98c2-ea975570e803.PNG)

**Comment by RITI8169** [comment] 2018-04-27 18:38
**Change the text in View Settings window**

![viewsettingstext](https://user-images.githubusercontent.com/31448327/39379232-818e58cc-4a0f-11e8-935a-313406bf2443.PNG)

**Comment by Temmermand** [comment] 2018-04-27 18:39
Validation is not saved for Grid questions.
1. Add a grid question to an existing survey.
2. Click validation on.
3. Save. 
4. Go back to my surveys.
5. reopen survey.
6. see that validation no longer appears on that question.

![image](https://user-images.githubusercontent.com/38793244/39379184-5e9cac56-4a0f-11e8-8b3d-962a48d1d17c.png)

![image](https://user-images.githubusercontent.com/38793244/39379198-6ab4e4a4-4a0f-11e8-8526-8fd33d7bd462.png)

![image](https://user-images.githubusercontent.com/38793244/39379225-79e921ec-4a0f-11e8-99ae-c87d905fa3e9.png)

![image](https://user-images.githubusercontent.com/38793244/39379266-92e2a1be-4a0f-11e8-904b-af926a48b5f3.png)

**Comment by sschwoppe** [comment] 2018-04-27 19:04
**Change File Type when Uploading Document on Website**

1. Create a survey on the website
2. Add a File Upload question
3. Select only one file type (in this example I used pptx)
4. Publish and open the survey on the website
5. Have to change the file type from Custom Files (which is the default file type) to All Files in order to select any pptx
6.  Finally, when a file is uploaded,  where does it go?
 
![upload](https://user-images.githubusercontent.com/8092111/39380329-328ca16c-4a2c-11e8-83e7-c81abe31b4e6.png)

![customfile](https://user-images.githubusercontent.com/8092111/39380335-38edc8c4-4a2c-11e8-83d3-23d6891f4566.png)

![allfiles](https://user-images.githubusercontent.com/8092111/39380348-41d44f44-4a2c-11e8-9b3e-228e7106c7fe.png)

**Comment by Temmermand** [comment] 2018-04-27 20:48
![image](https://user-images.githubusercontent.com/38793244/39384412-94bc848e-4a21-11e8-9479-83fd77497345.png)
 Looks like something is wrong with the ability to change the values

**Comment by Temmermand** [comment] 2018-04-27 20:50
Can report display labels instead of names? Seeing Choice 1 in the report (beta) is not that useful.

![image](https://user-images.githubusercontent.com/38793244/39384471-cc4915de-4a21-11e8-908d-cc2889314cc5.png)


![image](https://user-images.githubusercontent.com/38793244/39384530-f91fb504-4a21-11e8-9311-c392f22647c8.png)

**Comment by Temmermand** [comment] 2018-04-27 20:53
Likewise, trying to click the pencil to edit questions does nothing.

![image](https://user-images.githubusercontent.com/38793244/39384650-6bf030c2-4a22-11e8-86e5-418dc99513c5.png)

**Comment by RITI8169** [comment] 2018-04-27 21:03
**Using Duplicate functionality for Single choice grid questions does not work and the duplicated grid question does not display in the Preview or after publishing the survey**

1. Create a Survey
2. Add a Single Choice Grid question
3. Select the question and click on Duplicate
4. A copy of the question is created in the survey
5. Click on Preview and then Publish the survey

Neither the Preview nor the published survey shows the copied question. The only grid question displayed is the original one.

Design Mode:
![duplicate1](https://user-images.githubusercontent.com/31448327/39385051-c50744d8-4a23-11e8-9c51-b7c1f46529bb.PNG)

Published Survey:
![duplicate2](https://user-images.githubusercontent.com/31448327/39385053-c52c8cfc-4a23-11e8-8889-94822b47cbf9.PNG)

**Comment by RITI8169** [comment] 2018-04-27 21:11
Also, when using Duplicated Single Grid questions, the ordering of the other question gets messed up after publishing. Refer the screenshot above, "Name" question was on top of the survey form in Design mode but gets shifted down after publishing.

**Comment by RITI8169** [comment] 2018-04-27 21:14
**Change default text in Date textbox from M/d/yy to MM/DD/YY**

**Comment by RITI8169** [comment] 2018-04-27 21:28
**After deleting a copy of the grid question, it still shows the columns in the Data tab**

1. Create a Survey
2. Add a Single Choice Grid question
3. Duplicate the question
4. Now delete the copy of the question created
5. Publish the Survey
6. Submit some data 
7. Open the Data tab on the website

There are two occurrences of the choice columns given in the Grid question. One set has the data entered while the other comes up blank.

Data Tab:
![gridduplicate](https://user-images.githubusercontent.com/31448327/39385939-2812fc5e-4a27-11e8-8bbb-98b5aba0dab2.PNG)

Survey Design:
![gridduplicate2](https://user-images.githubusercontent.com/31448327/39385947-2d0c8be4-4a27-11e8-8d6a-85a35e546f15.PNG)

**Comment by Temmermand** [comment] 2018-04-27 21:29
It's not clear what instance name means, or how I would use it.

![image](https://user-images.githubusercontent.com/38793244/39386014-734228bc-4a27-11e8-8e20-088d67846233.png)

**Comment by Temmermand** [comment] 2018-04-27 21:37
Links icons in Dev site don't work like production.

![image](https://user-images.githubusercontent.com/38793244/39386231-7ddfbe32-4a28-11e8-85a0-029950903cec.png)


![image](https://user-images.githubusercontent.com/38793244/39386240-8d503216-4a28-11e8-97b4-bccf3ffc1bbe.png)

**Comment by zhif7782** [comment] 2018-04-28 13:05
Thank you for all the feedbacks.

@RITI8169 
* The additional row in field app is a known issue, will be fixed in future release
* Incorrect default Submitted Date in the S123 form on the website -> will be fixed in 2.8 release
* Logged your suggestion to the word cloud chart in our backlog, will be enhanced in future release
* "Incorrect location displayed for data submitted through S123 website form" 
  * I cannot reproduce the issue by following your steps. Please make sure the graphic symbol is in the wanted location before clicking the Submit button in the web app. If you are using the locate button on the map, please wait and only click the Submit button after you see the map moving to the correct location
* Change the text in View Settings window -> will fix before 2.8 release
* Using Duplicate functionality for Single choice grid questions does not work and the duplicated grid question does not display in the Preview or after publishing the survey -> will fix before 2.8 release
* when using Duplicated Single Grid questions, the ordering of the other question gets messed up after publishing -> will fix before 2.8 release
* Change default text in Date textbox from M/d/yy to MM/DD/YY -> will fix before 2.8 release
* After deleting a copy of the grid question, it still shows the columns in the Data tab -> will fix before 2.8 release

@Shimoorook 
* Duplicate and delete button will be fixed for Single Choice Grid question before 2.8 release


@Temmermand 
* Validation is not saved for Grid questions. -> will fix before 2.8 release
* Choices and questions should be disabled in Modify Schema after publishing the survey -> a known bug in dev repo, will fix before 2.8 release
* Can (print template) report display labels instead of names? -> a known bug in dev repo, actually it's just fixed today, will be available in 2.8 release :)
* Likewise, trying to click the pencil to edit questions does nothing. -> This is due to the question you are trying to edit is already published before, we have a known issue that the published question shoud be grayed out (especially for the new Single Choice Grid question) after publishing. Will apply the enhancement before 2.8 release
* Duplicate grid question doesn't work. Nothing happens when I click the button. -> will fix before 2.8 release
* Duplicate grids appear at the bottom as question 1, question 1, ... -> will fix before 2.8 release
* It's not clear what instance name means, or how I would use it. -> will improve the message in 3.0 release since string freezed for 2.8
* Links icons in Dev site don't work like production. -> will fix before 2.8 release


@sschwoppe 
* The file filter does not work in choose file dialog
* Uploaded file cannot be displayed in individual response

are two known issues in our dev repo, will fix both in 2.8 release, thanks!

**Comment by JohnHasthorpe** [comment] 2018-08-28 00:41
Closing issue for next round of Holistics.

**Closed by JohnHasthorpe** 2018-08-28 00:41 UTC
Labels: A - Website, v-2.8
