### ISSUE TITLE
CHALLENGE: Create a survey on the web designer with < or > symbol in any question label or choice label.

### ISSUE THREAD

**Issue by Shwujeng** [tedrick/Survey123-Testing#328] opened 2020-02-19 20:54 UTC
We had addressed an issue(BUG-000128390) in hotfix and now the fix is available in production https://survey123.arcgis.com/.
https://community.esri.com/groups/survey123/blog/2020/02/13/minor-update-to-the-survey123-website-and-web-app

Please follow the workflow and test it on https://survey123.arcgis.com/

- Create a survey on the web designer with > (greater-than sign) or < (less-than sign) in any question label or choice label.

- Make sure you can preview, save, publish and submit the survey.

- Make sure you can access to the Data tab to view the submitted data.

**Comment by BrandonArmstrong** [comment] 2020-02-20 18:00
Celine
Nicole

**Comment by nicsi76** [comment] 2020-02-20 18:31
When I use the multichoice and want to allow "other" in Edge I don't see in the settings that it is enabled but only in the preview of the survey. It seems to take a while to bring the tick while in Firefox it shows immediately.

**Comment by nicsi76** [comment] 2020-02-20 18:40
Did you think yet about using also drop-downs for single/multichoice questions? When you have more than 5 answer options the form becomes quite long very quickly (and it doesn't look very nice).

**Comment by nicsi76** [comment] 2020-02-20 18:50
In the schema I get the notice that I cannot use special characters only for the single-choice grid question but not for single-choice and mutliple choice questions.
![image](https://user-images.githubusercontent.com/11991954/74967928-9abe3780-5422-11ea-90e5-054c766d6f0f.png)

**Comment by nicsi76** [comment] 2020-02-20 19:00
For the info on the cache option for the question I get two mouse-tips. In Edge they are overlapping so you cannot read the full description, in Firefox on goes above and the other one below the button. But I would think one is enough. 
In Edge: 
![mousetip](https://user-images.githubusercontent.com/11991954/74968394-6eef8180-5423-11ea-87e0-f7759bf92eca.JPG)

In Firefox:
![mousetip_ff](https://user-images.githubusercontent.com/11991954/74968399-72830880-5423-11ea-906b-c1550eeff5d5.JPG)

Is the Answer saved for good? Can you also "un-cache" an answer? I wonder if there is a different term that could be used instead of caching that would make the explanation less necessary.

**Comment by cdore1** [comment] 2020-02-20 19:15
I managed to break my survey while working with <>.  I now receive this error message:
"The survey does not exist or is not accessible"

I added <> to Other option in Multiple choice with French characters.  I submitted the survey but when I clicked refresh on survey123 website to view the data, I got the aforementioned message.  I am going to see if I can reproduce again

**Comment by nicsi76** [comment] 2020-02-20 19:28
When I download and open the survey in connect the note that holds the survey description is stored in the hint instead of the label which makes connect complain about a missing label.

**Comment by cdore1** [comment] 2020-02-20 19:41
> I managed to break my survey while working with <>. I now receive this error message:
> "The survey does not exist or is not accessible"
> 
> I added <> to Other option in Multiple choice with French characters. I submitted the survey but when I clicked refresh on survey123 website to view the data, I got the aforementioned message. I am going to see if I can reproduce again

So I reproduced, when I click refresh on the Data tab, it break my survey.  Whether it's related to the <> choices, I am not positive.

**Comment by zhif7782** [comment] 2020-02-21 10:54
Hi @nicsi76 , thank you for all the feedback.

> When I use the multichoice and want to allow "other" in Edge I don't see in the settings that it is enabled but only in the preview of the survey. It seems to take a while to bring the tick while in Firefox it shows immediately.

I can reproduce the issue and logged a bug in the dev repo.

> Did you think yet about using also drop-downs for single/multichoice questions? When you have more than 5 answer options the form becomes quite long very quickly (and it doesn't look very nice).
(just saw that the web form recognizes the appearance of minimal for a select_one question when publishing it from Connect, so it should be possible ;-))

You can set a select_one or select_multiple question in Connect as the minimal appearance so that they will appear as a dropdown in the web app. Did you mean to have a "Dropdown (multiple choice) question type or support the similar minimal appearance from Connect for the Multiple Choice question type int the web designer?

> In the schema I get the notice that I cannot use special characters only for the single-choice grid question but not for single-choice and mutliple choice questions.

I can reproduce the issue and logged a bug in the dev repo.

> For the info on the cache option for the question I get two mouse-tips. In Edge they are overlapping so you cannot read the full description, in Firefox on goes above and the other one below the button. But I would think one is enough.

This is a known issue in the dev repo and I've added your feedback to the issue. (should be fixed soon)

> When I download and open the survey in connect the note that holds the survey description is stored in the hint instead of the label which makes connect complain about a missing label.

This is a by design behavior. Since the survey description from web designer has rich text content (alignment, image, paragraph...), we have to convert it to a note question hint rather than the label in XLSForm.

**Comment by zhif7782** [comment] 2020-02-21 11:01
Hi @nicsi76 , thank you for the feedback.

Would you mind sharing some detail steps to reproduce the issue? I published a survey from https://survey123.arcgis.com, with a Multiple Choice question which "Other" option label is `<> française`, when submitting a survey, I also use `<> française` as the answer for the "Other" option for the Multiple Choice question. The Data tab then works as expected for me.

![image](https://user-images.githubusercontent.com/7665168/75029228-9f472680-54dc-11ea-96bc-b6990f5c021b.png)

**Comment by nicsi76** [comment] 2020-02-21 11:20
Hi @zhif7782 
 
> Would you mind sharing some detail steps to reproduce the issue? I published a survey from https://survey123.arcgis.com, with a Multiple Choice question which "Other" option label is `<> française`, when submitting a survey, I also use `<> française` as the answer for the "Other" option for the Multiple Choice question. The Data tab then works as expected for me.
> 

That was reported by @cdore1 - I also could not reproduce this issue.

**Comment by nicsi76** [comment] 2020-02-21 11:22
Hi @zhif7782 , 
> 
> You can set a select_one or select_multiple question in Connect as the minimal appearance so that they will appear as a dropdown in the web app. Did you mean to have a "Dropdown (multiple choice) question type or support the similar minimal appearance from Connect for the Multiple Choice question type int the web designer?
> 
Yes, it would be nice to have the dropdown (=minimal appearance in connect) as an option also in the web designer. 


Thanks for the feedback on the other issues!

**Comment by zhif7782** [comment] 2020-02-21 11:40
@nicsi76 , thanks a lot for the additional information for the `<>` character issue.

For supporting equivalency of setting the minimal appearance for select_multiple question in the web designer, I've added your feedback to an existing issue in our backlog, will let you know when there is an update.

**Comment by nicsi76** [comment] 2020-02-21 11:41
@zhif7782 Thank you!

**Closed** 2020-05-11 23:18 UTC
Labels: A - Website, Type: Challenge, v-3.8
