### ISSUE TITLE
Feedback: Portal Enterprise Connection Sing in Error with Chrome

### ISSUE THREAD

**Issue by cwhitehe** [tedrick/Survey123-Testing#36] opened 2017-08-29 22:52 UTC
**Application:** _Survey 123 connected to Portal 10.5.1_

**Device:** _Dell Laptop_

**Operating System:** _Windows 10_

**Browser:** _Chrome_

**Error Description:**  Not able to sign into Survey 123 when connected to Portal environment in Chrome. Screenshot attached.

**How to reproduce:** Connect to Portal environment with Survey 123 and try to log in with Chrome browser.

**Have you tested with another survey?** N/A 

![image](https://user-images.githubusercontent.com/31450239/29847710-f53748e8-8cd1-11e7-992b-310be3800dce.png)

**Comment by tedrick** [comment] 2017-08-29 22:54
@zhif7782

**Comment by zhif7782** [comment] 2017-08-30 09:02
Hi @cwhitehe @tedrick , I'm trying to reproduce the issue by opening the page in Chrome: `http://survey123dev.arcgis.com?portalUrl=https://gisoneview-dev.fmi.com/portal`. However, seems I cannot access the portal URL: https://gisoneview-dev.fmi.com/portal

In addition, @cwhitehe can you provide the version and authentication of the portal? So I can find a similar one to reproduce the issue. Such as v10.5.1 and built-in security.

![image](https://user-images.githubusercontent.com/7665168/29864258-b253e80a-8da4-11e7-9bc3-4d66cefc5060.png)

**Comment by fcxagerr** [comment] 2017-09-12 19:33
The Portal version is 10.5.1 and uses SAML with ADFS for security.

**Comment by fcxagerr** [comment] 2017-09-12 20:58
The issue seems resolved in Google Chrome after a security certificate update. The problem persists in Internet Explorer however.

**Comment by zhif7782** [comment] 2017-09-13 03:06
Just FYI, one potential cause of the problem is that login will fail when a self-signed or non-trusted certificate is detected by the browser. You need to click the button shown below first to bypass the browser security check.

Is this what you've encountered?

![image](https://user-images.githubusercontent.com/7665168/30357839-72edf866-9873-11e7-9b38-17a30c1f3f94.png)
![image](https://user-images.githubusercontent.com/7665168/30357844-819362b6-9873-11e7-9a38-12f33609b7c9.png)

**Comment by fcxagerr** [comment] 2017-09-13 22:17
That seems to have been the issue. The problem was solved with a certificate update. The data tab displays just fine in Chrome now. Internet Explorer still cycles the user through authentication in the Data tab in Internet Explorer.

**Comment by zhif7782** [comment] 2017-09-14 06:25
Hi @fcxagerr , for the Internet Explorer, it works as expected for all surveys we've tested. If it only does not work for one survey, I think it's a survey related issue. You can confirm this by opening the Data page for different surveys in Internet Explorer.

If it's a survey related issue, we'd like to help if you can provide us enough information to debug, or investigate with support service will also help.

Thanks.

**Comment by fcxagerr** [comment] 2017-09-14 20:51
The problem seems to persist with multiple surveys and multiple users.

**Comment by fcxagerr** [comment] 2017-09-29 18:06
This issue appears to be resolved in Internet Explorer as well.

**Comment by zhif7782** [comment] 2017-09-30 08:34
@fcxagerr thanks for the feedback, good to know that!

**Comment by JohnHasthorpe** [comment] 2017-10-10 03:29
2.4 testing complete

**Closed** 2017-10-10 05:07 UTC
Labels: v-2.4
