### ISSUE TITLE
FEEDBACK: Update Notification(s)

### ISSUE THREAD

**Issue by BrandonArmstrong** [tedrick/Survey123-Testing#304] opened 2020-01-27 20:53 UTC
The following features have been added to Survey123 Connect and the Survey123 field app in v. 3.9

* Survey update notifications are now displayed on the gallery page and in the notification manager of the OS when survey updates are available
* The Download surveys page now alerts the user when updated surveys are available and provides a button to update all surveys in one action
* Selecting a survey from the gallery which has an update available will now prompt the user to update before continuing

Please test this out in your own environment by re-publishing surveys, or seeing if updates are available for surveys that you have access to but are not the owner of (i.e. a survey that has been shared with you via Group or in your Organization)

**Comment by BrandonArmstrong** [comment] 2020-01-30 17:32
Leonard
Bill W
Celine
Renee

**Comment by rbernstein80** [comment] 2020-01-30 18:21
Can the notification window show up in the center of the screen verses just show up on the top and disappearing. I was unable to read it before it disappeared. The red dots are nice as an additional notification, however I am not sure that this is enough of an indicator for the user to recognize it as the survey has been updated.

**Comment by rbernstein80** [comment] 2020-01-30 18:28
When I hit the Download Survey within the application the application crashed. I was trying to download the new edited surveys.

**Comment by DerekLaw** [comment] 2020-01-30 18:34
Quickly tested this functionality - seemed to work pretty well.

I had several surveys loaded on my phone; next I modified the surveys (making minor edits); in the mobile app - a red dot appears next to the updated/changed surveys (in the survey gallery). Doing some limited testing, it seems like the red dot only appears if I refresh the survey gallery page, or if I navigate away from the page and then return - is this expected behavior? or if I had waited long enough, would the red dot just appear?

**Comment by billwie** [comment] 2020-01-30 19:15
Client 3.9.124 iphone 7plus iOS v13.3.

I accepted the option to allow survey123 to show notifications but have seen no out of app notifications. overall it seems uneven in this platform, the only sure way to get an update notice is to go to the downloads folder. this is my testing script.

Form created in 3.7.62
Published to Portal 10.7.1 --- failed (time to log a ticket I guess) 
Published to AGOL
Downloaded to client 3.9.124 iphone 7plus iOS v13.3
submitted 2 suveys
returned to my survyes screen
Add 1 field in form (v2)
published
returned to client, opened form, submitted old form, no error/notification
Went to download surveys. Badge shown, Download updates shown at bottom.
returned to my surveys. badge that was not shown on survey before is now present.
Clicking on survey prompts to download update.
I updated survey to v2
Successfully submitted v2.
return to my surveys screen.
added select_one field in form (v3)
Published
Returned to client no badge displayed on my surveys page
force closed app (app picker, drag off screen)
launch app
Badge is shown
update survey
Sucessfully submitted V3.
stayed on survey page in client
add value to select_one (v4)
returned to client. no immediate change
returned to my surveys. No badge
selected different survey and returned to my surveys, no badge
selected survey. v3 not v4 offered.
submitted v3
returned to my suveys. no badge
Went to download surveys. Badge shown, Download updates shown at bottom.
returned to my surveys. badge that was not shown on survey appears briefly then dissapears.
Clicking on survey offers no message. v3 not v4 is available to submit.
submited v3
return to download
update survye to V4
submitted V4

**Comment by cdore1** [comment] 2020-01-30 19:31
If the app is opened, the update notification does not display until the app is refreshed.  I think this is by design but I already know that I have a client that is going to ask for a way around this

**Comment by kimberly-peter** [comment] 2020-01-30 20:09
I had to go to the Download survey page for the red dot to show up.  Shouldn't it just show up?
One time, the red dot showed up on the download page but when I went back to My Surveys it didn't show. I had to do it twice.
Tried with a survey published from web designer and one from Connect.

**Comment by lbarnhill** [comment] 2020-01-30 21:48
On IPad with IOS 13.3, the notification dot appeared on each survey loaded on this IPad.  Does installing an updated Survey123 Connect cause this?  I had only update one survey before checking the IPad.  Once I updated all surveys, the dots were gone and only reappear on the affected survey when I actually update the survey in Connect.  I like this feature and I was glad to hear the user can use existing surveys without updating - especially valuable if the user has pending surveys.  Tie this with the new banner notification  - I should be able to remind users to update only after they have submitted all pending surveys.

**Comment by BrandonArmstrong** [comment] 2020-01-30 22:21
@lbarnhill is it possible that there were updated versions of all surveys on the iPad since the last time you used it?  Upon opening the app, it will check each survey that is downloaded to the device to check if there are any updates available.  I'm thinking that, in fact, updates may have taken place for each of the previously downloaded surveys on the device.

**Comment by lbarnhill** [comment] 2020-01-30 22:28
It is not possible that every survey had been updated.  Some are older and have not been used for several months.  I have updated Connect on my laptop several times but I have not modified each and every survey.

I have also discovered that the notification red dot does not show on older installations of Survey123.  I had a version 3.7.56 just come in and it show no notification dots.  IOS is also 13.3 on this older iPad that just came in from the field.  I tried modifying one of the older surveys using 3.9 Connect downloaded today and the 3.7 field app still does not show a notification of update.


Leonard 
Barnhill, GISP

​GBA
9801 Renner Boulevard|Lenexa, KS 66219-9745
P (913) 577-8469
 
www.gbateam.com | LinkedIn | Facebook | Twitter

​CONFIDENTIALITY NOTICE: This e-mail message including attachments, if any, is intended for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message. Thank you.

**Comment by BrandonArmstrong** [comment] 2020-01-30 23:27
@lbarnhill The update notification (red dot) will only show in the 3.9 beta version of the field app and 3.9 beta v. of Survey123 Connect.  As a test, maybe you can install the 3.9 beta v. on another device.  

The intended behavior is that an update notification (red dot) will be present for all surveys (in field app) that have a newer version **of the survey** available than the one that currently exists on the device.  This notification will not be present on any version of the field app or Connect prior to beta 3.9

In regards to the initial behavior that you reported "all surveys have a red dot", was this in the field app on your iPad?  Did you uninstall v. 3.7 before installing beta v. 3.9?  One way you might test is to
 
1. uninstall v.3.9 on the iPad
2. re-install v. 3.7
3. download several surveys from the Downloads Surveys menu
4. update one of the downloaded surveys using Survey123 Connect (re-publish)
5. update the field app to v.3.9
6. Do you see notification for all surveys on the device or just the one that was re-published with Connect?

**Comment by Bark0s** [comment] 2020-01-31 02:07
My test:
Signed in as a new user for the first time on a device. (I have signed in previously as another user and have 2 red dotted surveys existing on the device)  
I get a notification that there's 1 updated survey.
I click the notification, nothing happens, it just disappears, it doesn't take me anywhere.  (it would be good to take me to the download page)
I browse to the survey downloads and there are no red dotted surveys for download.  The survey I just published IS available but it does not have a red dot.

**Comment by jbickmore** [comment] 2020-01-31 03:32
AMAZING
Was very impressed when I saw this today
Thank you

**Comment by someevil** [comment] 2020-01-31 03:32
Am loving this new feature, working very well in all platforms tested, Survey123 for ArcGIS and the ios app. No problems to report. 
I agree with an already raised idea, I would love to have the option as the survey creator to 'force' user to update, make an update compulsory if I think it should be. Otherwise let the user choose

**Comment by lbarnhill** [comment] 2020-01-31 14:41
Good morning Brandon,
I retested the Beta version based on your directions below.  The notification (red dot) appears only on the survey I had updated since reinstalling v3.9 on the iPad this morning.  The currently installed Survey123 was downloaded from TestFlight and shows version 3.9.124

The previous testing was completed by installing v3.9 from TestFlight without removing the previous version.  The version uninstalled this morning showed version 3.9.113b (a Greek “b”).


Leonard 
Barnhill, GISP

​GBA
9801 Renner Boulevard|Lenexa, KS 66219-9745
P (913) 577-8469
 
www.gbateam.com | LinkedIn | Facebook | Twitter

​CONFIDENTIALITY NOTICE: This e-mail message including attachments, if any, is intended for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message. Thank you.

**Comment by mcavoye** [comment] 2020-02-07 19:55
I've tested this pretty thoroughly. Works great! deleted questions, altered field types etc. All work great for updated surveys!
I would also like a feature to force update to new surveys.

**Comment by tedrick** [comment] 2020-05-11 23:17
Thanks all for feedback.  Closing out issue.

**Closed by tedrick** 2020-05-11 23:17 UTC
Labels: A - Connect, A - Field App, Type: Feedback, v-3.9
