### ISSUE TITLE
Challenge: Require your survey to be updated to latest version

### ISSUE THREAD

**Issue by brettstokes** [tedrick/Survey123-Testing#339] opened 2020-05-13 05:44 UTC
### Challenge
Ensure users cannot submit data to an individual survey unless they use the latest published version. Create an new survey (or use an existing survey) and download to your device. Make a change to your survey,  enable the require update setting and re-publish. Try submitting data to this survey.

### How do I require my survey users to download updates before submitting data?
This requirement can enabled / disabled for individual surveys:
- In the Survey123 beta website under 'Organization':
<img width="652" alt="Screen Shot 2020-05-13 at 9 39 33 AM" src="https://user-images.githubusercontent.com/1319289/81840451-e0f4d580-94fd-11ea-9551-3c46519a9508.png">

- In Connect via the survey Settings → General tab. A new drop down option "Require update" has been added to the bottom of this page. This Connect setting will be disabled by default. You will need to republish your survey after changing it, and it is only honored if your admininstrators have not already applied the requirement to all surveys in your organization.

![image](https://user-images.githubusercontent.com/46305628/81775237-ccc9cc00-952f-11ea-8ec0-48429e0d1800.png)

### What do users see in the field app?
If a survey has been configured to require updates (via Organization setting or Survey setting) they will see a different "Update Required" pop-up when launching the survey from the gallery. This pop-up does not give the option to "Continue without update", so the user must update the survey or return to the gallery.

![image](https://user-images.githubusercontent.com/46305628/81775599-79a44900-9530-11ea-8b9d-3888959683ab.png)

**Comment by Shwujeng** [comment] 2020-05-13 22:09
Redlands holistic lab session participants (5/14/2020):
Please check your name if you are interested in testing this feature.

- [ ] Adrienne Allegretti
- [ ] Aldous Tsang
- [ ] Bobby Home
- [ ] Brandon Whitney
- [ ] Carlos Maulen
- [ ] Chad Nunemacher
- [ ] Charmel Menzel
- [ ] Chris Lesueur
- [ ] Christopher Eby
- [ ] Cory Whittaker
- [ ] Dabney Hopkins
- [ ] Jerry Jacobsen
- [ ] Juliano Kersting
- [ ] Kevin Deege
- [ ] Kyle Jones
- [ ] Kyle Wikstrom
- [ ] Kylie Donia
- [ ] Leonard Barnhill
- [ ] Michael Penokie
- [ ] Mike Cox
- [ ] Nichole Ueberschar
- [ ] Steven Temmermand
- [ ] Theresa Maier
- [ ] Zachary Sutherby

**Comment by Temmermand** [comment] 2020-05-14 18:10
It seems like the first time i made a required update to a survey in the beta Windows app, the update closed the Windows app. However, when I tried again, I was unable to reproduce the issue and the update worked fine.

**Comment by Temmermand** [comment] 2020-05-14 18:17
same issue happened again. One update closed the Windows app. The next update worked fine. Seems like there might be stability issues with the required update. I tried to hit "return" four times before accepting the required update. That repro'd the closing of the Windows app once, but not the second time.

**Comment by MichalKEsri** [comment] 2020-05-14 18:18
After a few minutes of working the page become inactive and greyout:
![s1](https://user-images.githubusercontent.com/65359966/81970632-b0339f80-95d4-11ea-85cd-8a874fdb05e3.png)

**Comment by Zachary-Sutherby** [comment] 2020-05-15 17:26
One very minor thing about the survey updates in the Field App and this is present in 3.9 as well so it's not 3.10 specific. 

Prior to 3.9 and the introduction of survey update alerts the workflow to update surveys was to navigate back to Download Surveys and select the refresh icon. 

![DownloadSurveys](https://user-images.githubusercontent.com/54078266/82076265-6dd09800-9692-11ea-8837-2292dfaf1129.JPG)

With the new workflow to update surveys using the notification, the first thing I see is the refresh icon. If I only have one survey that needs to be updated and I select the refresh icon the Update Surveys page stays at that screen and does not automatically redirect back to the My Surveys page. 

![Survey123Updategif](https://user-images.githubusercontent.com/54078266/82078490-04eb1f00-9696-11ea-8f67-3aba721b1b62.gif)

I know if I just select Download updates: 1 at the bottom that will automatically redirect me back to my surveys but it would be nice to have that redundancy if I only have one survey to update and I select the refresh icon it would do the same thing as the download updates button. 

I know with multiple surveys this is not ideal as I would expect the Field App to remain on the update surveys page so I can pick and choose what surveys are updated.

**Closed** 2020-06-03 17:33 UTC
Labels: A - Connect, A - Field App, Priority, Type: Challenge
