### ISSUE TITLE
Survey123 Field App crashes when submitting a survey where the audio file has been renamed

### ISSUE THREAD

**Issue by bethanyw** [tedrick/Survey123-Testing#25] opened 2017-08-29 18:28 UTC
**Application:** Survey123 Field App

**Device:** Windows computer

**Operating System:** Windows 7 Enterprise; SP1

**Browser:** N/A

**Error Description:** 

When submitting the survey, Survey123 crashes with the following message:

"Survey123forArcGIS.exe has stopped working. A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available."

**How to reproduce:**

1) Download the audio.xlsx form provided on the Early Adopter Community page
2) Launch Survey123 Connect 2.4.32 and connect to the survey123dev api
3) Create a new survey using the audio.xlsx form
4) Publish this survey to ArcGIS Online
5) Download the survey in the Survey123 Windows field app (version 2.4.52)
6) Fill out the survey; record 30 seconds of audio in the audio question
7) Click on the name of the audio recording to change it's name. Example: "testaudionamechange"
8) Submit the survey
9) App crashes

[Survey123ConnectforArcGIS-20170829-131813.zip](https://github.com/tedrick/Survey123-Testing/files/1261310/Survey123ConnectforArcGIS-20170829-131813.zip)

Note: I have attached the diagnostics logs.

**Have you tested with another survey?** 

Yes, I created another xlsx form with one audio question and reproduce the issue.

**Comment by IsmaelInRedlands** [comment] 2017-08-29 20:11
@bethanyw  This looks like a Windows specific problem. Would you please report if you can reproduce the problem in Android or iOS?

**Comment by bethanyw** [comment] 2017-08-29 20:29
Hi @IsmaelInRedlands, thanks for your message. I don't currently have access to an Android device. I just tested it on the new app in iOS and I reproduced the issue when I used a long file name (37 characters)

**Comment by odibie** [comment] 2017-08-29 23:57
@spatialdude - please see.  This crashes on initial submission, but subsequent submission from the outbox works

**Comment by phil-wilson** [comment] 2017-09-27 05:51
Issue with renaming audio files on Windows has been addressed and will be resolved in the 2.5 release as per https://devtopia.esri.com/Melbourne/Survey123/issues/1809#issuecomment-883060

**Closed** 2017-09-27 05:51 UTC
